config/routes.rb
GestionVisitas::Application.routes.draw do
  get "static_pages/home"

  resources :assists

  resources :events

  resources :companies

  resources :countries

  resources :states

  resources :works

  resources :people

  root :to => 'static_pages#home'

end

app/models/assist.rb
class Assist < ActiveRecord::Base
  attr_accessible :event_id, :person_id, :present

  belongs_to  :event
  belongs_to  :person

  validates_presence_of  :event_id, :person_id
  validates_inclusion_of :present, :in => [true, false]

end

app/controllers/assists_controller.rb
class AssistsController < ApplicationController
  # GET /assists
  # GET /assists.json
  def index
    @assists = Assist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assists }
    end
  end

  # GET /assists/1
  # GET /assists/1.json
  def show
    @assist = Assist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assist }
    end
  end

  # GET /assists/new
  # GET /assists/new.json
  def new
    @assist = Assist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assist }
    end
  end

  # GET /assists/1/edit
  def edit
    @assist = Assist.find(params[:id])
  end

  # POST /assists
  # POST /assists.json
  def create
    @assist = Assist.new(params[:assist])

    respond_to do |format|
      if @assist.save
        format.html { redirect_to @assist, notice: 'Assist was successfully created.' }
        format.json { render json: @assist, status: :created, location: @assist }
      else
        format.html { render action: "new" }
        format.json { render json: @assist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assists/1
  # PUT /assists/1.json
  def update
    @assist = Assist.find(params[:id])

    respond_to do |format|
      if @assist.update_attributes(params[:assist])
        format.html { redirect_to @assist, notice: 'Assist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assists/1
  # DELETE /assists/1.json
  def destroy
    @assist = Assist.find(params[:id])
    @assist.destroy

    respond_to do |format|
      format.html { redirect_to assists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assists_helper.rb
module AssistsHelper
end

app/views/assists/_form.html.erb
<%= form_for(@assist) do |f| %>
  <% if @assist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assist.errors.count, "error") %> prohibited this assist from being saved:</h2>

      <ul>
      <% @assist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.number_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :present %><br />
    <%= f.check_box :present %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assists/edit.html.erb
<h1>Editing assist</h1>

<%= render 'form' %>

<%= link_to 'Show', @assist %> |
<%= link_to 'Back', assists_path %>

app/views/assists/index.html.erb
<h1>Listing assists</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Person</th>
    <th>Present</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assists.each do |assist| %>
  <tr>
    <td><%= assist.event_id %></td>
    <td><%= assist.person_id %></td>
    <td><%= assist.present %></td>
    <td><%= link_to 'Show', assist %></td>
    <td><%= link_to 'Edit', edit_assist_path(assist) %></td>
    <td><%= link_to 'Destroy', assist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assist', new_assist_path %>

app/views/assists/new.html.erb
<h1>New assist</h1>

<%= render 'form' %>

<%= link_to 'Back', assists_path %>

app/views/assists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @assist.event_id %>
</p>

<p>
  <b>Person:</b>
  <%= @assist.person_id %>
</p>

<p>
  <b>Present:</b>
  <%= @assist.present %>
</p>


<%= link_to 'Edit', edit_assist_path(@assist) %> |
<%= link_to 'Back', assists_path %>